name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Who am I 1
        run: whoami

      - uses: actions/checkout@v2

      - name: Who am I 1
        run: whoami

#      - name: Update APT
#        run: sudo apt --yes update
#
#      - name: Install CMake
#        run: sudo apt --yes install cmake

      - name: Install Bluez
        run: sudo apt --yes install bluez

      - name: Configure CMake
        run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
