name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Types: Debug, Release, RelWithDebInfo, MinSizeRel.
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up AWS self-host
        run: ${{github.workspace}}/aws/setup.sh

      - name: CMake3 - Configure
        run: >
          cmake3 \
            -S ${{github.workspace}}/src \
            -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake3 - Build
        run: >
          cmake3 \
            --build ${{github.workspace}}/build \
            --config ${{env.BUILD_TYPE}}

      - name: CMake3 - Test
        working-directory: ${{github.workspace}}/build
        run: ctest3 -C ${{env.BUILD_TYPE}}

      - name: Get binary's name
        run: |
          PROJECT_NAME=$(grep PROJECT_NAME \
            ${{github.workspace}}/build/CMakeCache.txt \
            | cut -d "=" -f2)
          echo "BINARY_NAME=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Archive binary's built
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{github.workspace}}/build/${{ env.BINARY_NAME }}
