name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Cmake3 - Install
        run: sudo yum --assumeyes install cmake3

      - name: Cmake - Remove
        run: sudo yum --assumeyes remove cmake.x86_64

      - name: Cmake - List packages
        run: sudo yum list cmake*

      - name: Bluez - Install
        run: sudo yum --assumeyes install bluez

      - name: CMake3 - Configure
        run: >
          cmake3 \
            -S ${{github.workspace}}/src \
            -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake3 - Build
        run: >
          cmake3 \
            --build ${{github.workspace}}/build \
            --config ${{env.BUILD_TYPE}}

      - name: CMake3 - Test
        working-directory: ${{github.workspace}}/build
        run: ctest3 -C ${{env.BUILD_TYPE}}
